"""create tour_departure_price, add unique constraint and CunrrencyType Enum

Revision ID: 84ebea820e38
Revises: baa40e1860ab
Create Date: 2026-09-30 15:59:57.689495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84ebea820e38'
down_revision: Union[str, Sequence[str], None] = 'baa40e1860ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
currency_type_enum = postgresql.ENUM(
    'VND', 'USD', 'EUR', 
    name='currencytype', 
    schema='tour'
)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    currency_type_enum.create(op.get_bind(), checkfirst=True)
    op.create_table('tour_departure_price',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('departure_id', sa.Uuid(), nullable=False),
    sa.Column('passenger_type', sa.Enum('ADULT', 'CHILD', 'INFANT', 'SINGLE_SUPPLEMENT', name='passengertype', schema='tour'), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['departure_id'], ['tour.tour_departure.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='tour'
    )
    op.create_index(op.f('ix_tour_tour_departure_price_departure_id'), 'tour_departure_price', ['departure_id'], unique=False, schema='tour')
    op.drop_index(op.f('ix_tour_tour_departure_code'), table_name='tour_departure', schema='tour')
    op.create_index(op.f('ix_tour_tour_departure_code'), 'tour_departure', ['code'], unique=True, schema='tour')
    op.add_column('tour_template', sa.Column('currency_type', sa.Enum('VND', 'USD', 'EUR', name='currencytype', schema='tour'), nullable=False), schema='tour')
    op.drop_index(op.f('ix_tour_tour_template_name'), table_name='tour_template', schema='tour')
    op.create_index(op.f('ix_tour_tour_template_name'), 'tour_template', ['name'], unique=True, schema='tour')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tour_tour_template_name'), table_name='tour_template', schema='tour')
    op.create_index(op.f('ix_tour_tour_template_name'), 'tour_template', ['name'], unique=False, schema='tour')
    op.drop_column('tour_template', 'currency_type', schema='tour')
    op.drop_index(op.f('ix_tour_tour_departure_code'), table_name='tour_departure', schema='tour')
    op.create_index(op.f('ix_tour_tour_departure_code'), 'tour_departure', ['code'], unique=False, schema='tour')
    op.drop_index(op.f('ix_tour_tour_departure_price_departure_id'), table_name='tour_departure_price', schema='tour')
    op.drop_table('tour_departure_price', schema='tour')
    # ### end Alembic commands ###
    currency_type_enum.drop(op.get_bind(), checkfirst=True)