"""update tour schema

Revision ID: baa40e1860ab
Revises: 6c719739e361
Create Date: 2026-09-29 12:52:52.715583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'baa40e1860ab'
down_revision: Union[str, Sequence[str], None] = '6c719739e361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        CREATE TYPE tour.tourboundarytype AS ENUM ('DOMESTIC', 'INBOUND', 'OUTBOUND', 'CROSS_BORDER')
    """)
    op.add_column('tour_template', sa.Column('boundary_type', sa.Enum('DOMESTIC', 'INBOUND', 'OUTBOUND', 'CROSS_BORDER', schema='tour', name='tourboundarytype'), nullable=False), schema='tour')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tour_template', 'boundary_type', schema='tour')
    op.execute("""
        DROP TYPE tour.tourboundarytype;
    """)
    # ### end Alembic commands ###
