"""update DomainBaseModel

Revision ID: 30771713a094
Revises: 16588a6be920
Create Date: 2026-07-09 20:21:33.168263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30771713a094'
down_revision: Union[str, Sequence[str], None] = '16588a6be920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('created_at', sa.DateTime(), nullable=False), schema='user')
    op.add_column('organization', sa.Column('updated_at', sa.DateTime(), nullable=False), schema='user')
    op.add_column('organization', sa.Column('deleted_at', sa.DateTime(), nullable=True), schema='user')
    op.add_column('organization_member', sa.Column('created_at', sa.DateTime(), nullable=False), schema='user')
    op.add_column('organization_member', sa.Column('updated_at', sa.DateTime(), nullable=False), schema='user')
    op.add_column('organization_member', sa.Column('deleted_at', sa.DateTime(), nullable=True), schema='user')
    op.create_foreign_key(None, 'organization_member', 'user', ['user_id'], ['id'], source_schema='user', referent_schema='user', ondelete='CASCADE')
    op.create_foreign_key(None, 'organization_member', 'organization', ['organization_id'], ['id'], source_schema='user', referent_schema='user', ondelete='CASCADE')
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False), schema='user')
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=False), schema='user')
    op.add_column('user', sa.Column('deleted_at', sa.DateTime(), nullable=True), schema='user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'deleted_at', schema='user')
    op.drop_column('user', 'updated_at', schema='user')
    op.drop_column('user', 'created_at', schema='user')
    op.drop_constraint(None, 'organization_member', schema='user', type_='foreignkey')
    op.drop_constraint(None, 'organization_member', schema='user', type_='foreignkey')
    op.drop_column('organization_member', 'deleted_at', schema='user')
    op.drop_column('organization_member', 'updated_at', schema='user')
    op.drop_column('organization_member', 'created_at', schema='user')
    op.drop_column('organization', 'deleted_at', schema='user')
    op.drop_column('organization', 'updated_at', schema='user')
    op.drop_column('organization', 'created_at', schema='user')
    # ### end Alembic commands ###
