"""tour

Revision ID: 6c719739e361
Revises: 30771713a094
Create Date: 2026-09-04 14:29:38.605686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c719739e361'
down_revision: Union[str, Sequence[str], None] = '30771713a094'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS tour')
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_type t
                JOIN pg_namespace n ON n.oid = t.typnamespace
                WHERE t.typname = 'role' AND n.nspname = 'user'
            ) THEN
                CREATE TYPE "user".role AS ENUM ('ADMIN', 'MANAGER', 'MEMBER');
            END IF;
        END $$;
    """)
    op.execute('ALTER TABLE "user".organization_member ALTER COLUMN role TYPE "user".role USING role::text::"user".role')
    op.execute('DROP TYPE IF EXISTS public.role CASCADE')
    op.execute('DROP TYPE IF EXISTS public.servicetype CASCADE')
    op.execute('DROP TYPE IF EXISTS public.tourstatus CASCADE')
    op.create_table('service',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('service_type', sa.Enum('HOTEL', 'TRANSFER', 'MEAL', 'ACTIVITY', 'GUIDE', name='servicetype', schema='tour'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tour'
    )
    op.create_index(op.f('ix_tour_service_name'), 'service', ['name'], unique=False, schema='tour')
    op.create_table('tour_category',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tour'
    )
    op.create_index(op.f('ix_tour_tour_category_name'), 'tour_category', ['name'], unique=True, schema='tour')
    op.create_table('tour_template',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('total_days', sa.Integer(), nullable=False),
    sa.Column('total_nights', sa.Integer(), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'CLOSED', name='tourstatus', schema='tour'), nullable=False),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='tour'
    )
    op.create_index(op.f('ix_tour_tour_template_name'), 'tour_template', ['name'], unique=False, schema='tour')
    op.create_index(op.f('ix_tour_tour_template_template_code'), 'tour_template', ['template_code'], unique=False, schema='tour')
    op.create_table('itinerary_day',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['tour.tour_template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='tour'
    )
    op.create_table('template_category',
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['tour.tour_category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['tour.tour_template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('template_id', 'category_id'),
    schema='tour'
    )
    op.create_table('tour_departure',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('max_capacity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['tour.tour_template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='tour'
    )
    op.create_index(op.f('ix_tour_tour_departure_code'), 'tour_departure', ['code'], unique=False, schema='tour')
    op.create_index(op.f('ix_tour_tour_departure_start_date'), 'tour_departure', ['start_date'], unique=False, schema='tour')
    op.create_table('tour_template_service',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('service_id', sa.Uuid(), nullable=False),
    sa.Column('is_included', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['tour.service.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['tour.tour_template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='tour'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tour_template_service', schema='tour')
    op.drop_index(op.f('ix_tour_tour_departure_start_date'), table_name='tour_departure', schema='tour')
    op.drop_index(op.f('ix_tour_tour_departure_code'), table_name='tour_departure', schema='tour')
    op.drop_table('tour_departure', schema='tour')
    op.drop_table('template_category', schema='tour')
    op.drop_table('itinerary_day', schema='tour')
    op.drop_index(op.f('ix_tour_tour_template_template_code'), table_name='tour_template', schema='tour')
    op.drop_index(op.f('ix_tour_tour_template_name'), table_name='tour_template', schema='tour')
    op.drop_table('tour_template', schema='tour')
    op.drop_index(op.f('ix_tour_tour_category_name'), table_name='tour_category', schema='tour')
    op.drop_table('tour_category', schema='tour')
    op.drop_table('service', schema='tour')
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM pg_type t
                JOIN pg_namespace n ON n.oid = t.typnamespace
                WHERE t.typname = 'role' AND n.nspname = 'public'
            ) THEN
                CREATE TYPE public.role AS ENUM ('ADMIN', 'MANAGER', 'MEMBER');
            END IF;
        END $$;
        ALTER TABLE "user".organization_member ALTER COLUMN role TYPE public.role USING role::text::public.role;
        DROP TYPE IF EXISTS "user".role CASCADE;
        DROP TYPE IF EXISTS "tour".servicetype CASCADE;
        DROP TYPE IF EXISTS "tour".tourstatus CASCADE;
        DROP SCHEMA IF EXISTS tour CASCADE;
    """)
    # ### end Alembic commands ###
